;;
;; Copyright (c) Microsoft Corporation. All rights reserved. 
;; 
;; You may only use this code if you agree to the terms of the ProjectOZ License agreement (see License.txt).
;; If you do not agree to the terms, do not use the code.
;;

    BASICSERV_NOSTACK_BUGCHECK                  equ      99     ; no stack
    BASICSERV_NOSTACK_SLEEP                     equ       0     ; no stack
    BASICSERV_NOSTACK_WAKEUP                    equ       1     ; no stack

    BASICSERV_foo                               equ      13

    BASICSERV_ConsolePrint                      equ      80
    BASICSERV_ConsoleGetline                    equ      81

