#
# Copyright (c) Microsoft Corporation. All rights reserved. 
# 
# You may only use this code if you agree to the terms of the Windows Research Kernel Source Code License agreement (see License.txt).
# If you do not agree to the terms, do not use the code.
# 

definc = ..\INC

deviceobjs = \
	$(OBJ)\Devices.obj

DEVICES\Devices.c:	Defs.h Debug.h $(definc)\DeviceDefs.h

defs = -I$(definc)

